apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  annotations:
    kubernetes.io/ingress.class: "nginx" 
    #nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "le-prod" 
spec:
  tls:
  - hosts:
    - {{ .Values.service.domain }}
    secretName: "{{ .Release.Name }}-ingress-secret"
  rules:
  - host: {{ .Values.service.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-svc"
            port:
              number: 80