apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.service.domain }}`) 
    kind: Rule
    services:
    - name: {{ .Chart.Name }}
      port: 80