apiVersion: v1
kind: Service
metadata:
  name: svc-{{.Chart.Name }}
  labels:
    stage: dev
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    stage: dev
