name: creating container
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      IMAGENAME: chaski-api
      STAGE: dev
    steps:
      - name: "configuring imageName"
        run: |
          if [ "${{ github.ref }}" = "refs/heads/dev" ];
          then
              IMAGENAME=$IMAGENAME-$STAGE
          elif [ "${{ github.ref }}" = "refs/heads/staging" ];
          then
              STAGE=pre
              IMAGENAME=$IMAGENAME-$STAGE
          elif [ "${{ github.ref }}" = "refs/heads/master" ];
          then
              STAGE=prod
              IMAGENAME=$IMAGENAME-$STAGE
          else
              echo "incorrect branch"
              exit 1
          fi
      - name: "building image"
        run: docker build -t $IMAGENAME-$STAGE:${{ github.sha }} .

