name: creating container
on: [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      IMAGENAME: chaski-api
      STAGE: dev
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: docker login
        run: echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin 
      - name: building image
        run: docker build -t $IMAGENAME .
      - name: "tagging image"
        run: |
          if [ "${{ github.ref }}" = "refs/heads/dev" ];
          then
              STAGE=dev
          elif [ "${{ github.ref }}" = "refs/heads/staging" ];
          then
              STAGE=pre
          elif [ "${{ github.ref }}" = "refs/heads/master" ];
          then
              STAGE=prod
          else
              echo "incorrect branch"
              exit 1
          fi
          FULLIMAGE=${{ github.repository }}/$IMAGENAME-$STAGE:${{ github.sha }}
          docker tag $IMAGENAME $FULLIMAGE
          docker push $FULLIMAGE

